apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook-mutating
webhooks:
  - name: webhook-mutating.webhook-test.svc
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded # Call webhook again if object is mutated
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook-validating
        namespace: webhook-test
        path: "/mutate-pods"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrVENDQXVHZ0F3SUJBZ0lVRWx6cWZmVXpiQ1FEMGZTTlhmQ2JsSGZ6Yndjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERXNNQ29HQTFVRUF3d2pkMlZpYUc5dmF5MTJZV3hwClpHRjBhVzVuTG5kbFltaHZiMnN0ZEdWemRDNXpkbU13SGhjTk1qTXdOREF6TVRNME5UQTVXaGNOTWpRd05EQXkKTVRNME5UQTVXakJ6TVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4RwpBMVVFQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRIa2dUSFJrTVN3d0tnWURWUVFERENOM1pXSm9iMjlyCkxYWmhiR2xrWVhScGJtY3VkMlZpYUc5dmF5MTBaWE4wTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMTWluNXNXZTJBQm9UT1VjRXV0cWxDM2R1WTU1MEMzTnNwTG5uWlJObThuM2NleQpUR2hSNEo1aEw2RjhTNm94cFBSQUQ5UGErd2NYcHJmUG9WUXQ4cUJvUXdNUUNnZmRFTWJDMGViL2xNdlpKOTdxCkNuRnYwTjNZZTNmTlBMQVZ3SXV4UE9NcFhoSU85Rno5dXFsUVpKb0V5WGNoUFFOUnp1ZUpzQ1JrNGdUUXhTVSsKa1N0QzNYcVdJMVdvMW55bTYrOUphRW9rSzBFSFZtYnQ4azJZZmErb2tXMmlSMFVPN2gzRzNJUWpqcTZGak1xcwpCd3NMeDh1ZVZsNk0rcVFUL1kwWnJROW9ubmZGMnVKcnFsTktPRzRJaFMrOFNvdU9lTWNyTjR3aHZCRVF2UlZ1Cms1QlFBeE5yMnBIOG1ta2FZUGpqY1FVTG50Z3d6alJvUUphaGhrc0NBd0VBQWFPQmhEQ0JnVEFkQmdOVkhRNEUKRmdRVUUveGFxbkEwaUxNdVF5MEJUakxYaWRPWkdhRXdId1lEVlIwakJCZ3dGb0FVRS94YXFuQTBpTE11UXkwQgpUakxYaWRPWkdhRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QXVCZ05WSFJFRUp6QWxnaU4zWldKb2IyOXJMWFpoCmJHbGtZWFJwYm1jdWQyVmlhRzl2YXkxMFpYTjBMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVFRQjAKbkkzRCs4QjVpNytSdkRZOENjaHB1ZHBXNUtNM1RHcW9Zb01QanlsVHVQSWpjUUN2cTZLTDRGMWU5Z2R0VVFUcwp0Uk51Rm16VGFVRSt0M0VGQnZFcXppMUtENnpLWXZVTW85aU5ZSmVwVmFCVjFIMGNvTHVSMC9JZDEzb2VJalluCnJIUjAxc21LYlVBdTNBTkg3aE9ybS9sd2VEMEc4MEtDVTg3QUlqTVYxVTVPUm5FSjBJTzd5MUdSRDg1WktFRDkKcUZqdHNiejZSUkV0VHJLRnkwSWhmckFyZCtPeUN0bFU4Qm05c2lmaWNkRXRqNkRwOW9uaXpKN1BUR1M1M0d6ago3NnAzWXgyQzJMZkdRZnF5dUlPMEl0cVhrQmdVMFY4bjRka2l5bC9EU0xwcWJ3b2FIcS9nRGI4N3BpV28zeFRNCmNLQ3lVN0k2SFNqOGRieHQvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
