apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: iptables-lo-webhook
webhooks:
  - name: iptables-lo-svc.iptables-lo-system.svc
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded # Call webhook again if object is mutated
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: iptables-lo-svc
        namespace: iptables-lo-system
        path: "/iptables-apply"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVR2pvTWZPUEtNNUpwRitlUndyR0k1aUl2a080d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TXpBNE1UUXhNelE1TURSYUZ3MHlOREE0Ck1UTXhNelE1TURSYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREpDVzV6WHovVkpMWHpabUNCWnJITVFMZUtqK3NzOUdIQllDeExHYiswCjV0MU5mblBTV2VOMTlHTG5kbCtPY2dYdEN2MzgzT1U0b29GeGxzMXhlRm0zSFVYanhQWnVKZEFpUjZBSGxaVFIKWFNNM0t4eUhUMHAwM2l4NUNBR20zSHZVcUhLOUJNSjdOSVQzY0V5UGRXQ3lqeFdkSkF5VTl2T3Y0bUJhWTVuQgo5dXVjV2k3dzJzMytqaVRyTklGYVZsL0tIMXAvQmJWeE1vNmQ2ZTRxSzNPNWJiTnJoc2pOZWplb1FQMkRuVkUvClIxenYzbVFrMHJyZVpiVUhpMzZOMU80ekRwemhrODBuV0dVeG4rM2pBTjh4RVREY1ZQQVhYSjhFZDZTdlZjZncKcnlad1NqM1pva1R4SXdLTnNFNVBjVmxaZnVFQ2VEbTd5eGZPeHhoeHZQZ05BZ01CQUFHamdZY3dnWVF3SFFZRApWUjBPQkJZRUZLWGcvUW5KYnpIS25yTko2K05FUkhLRUhtUHdNQjhHQTFVZEl3UVlNQmFBRktYZy9RbkpiekhLCm5yTko2K05FUkhLRUhtUHdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdNUVlEVlIwUkJDb3dLSUltYVhCMFlXSnMKWlhNdGJHOHRjM1pqTG1sd2RHRmliR1Z6TFd4dkxYTjVjM1JsYlM1emRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUg1R3d4L3pMdFNpUmgvMWdISHlMdHJML1ZhcVBVZ1FsdkY0VnVMQWthUE5PZmlKRm5HUndPbDF1RHV1ClFQZlFteGtSUEZFbmkxaXdSdUljNnFEdFAwM0EvSURjWHJOS1VzZ3NQdkJ6clc0MFluM0NDN1NvMlRnMERRcFMKOUhTTXlGTVhOOXhQOWVaV3JoSUhCdlFJd2JZTHMxMTQyU0F6dGFCSVRnUFI2ZlFNZnI3SFdZck5Zb2I3K1ZxVgp0M1NITSttYUtXZU5vcVFZcVc0VHVPS0pMMWFNQnNteU5obGozTGVrK1R4Yk4ybThHVFpYTnNpU0MyVHJPUC9uCm5TSUY2cFRNelBSR0Q0a2FiNlB4UHIvR2ZEeHgxYnNGcEt2b1AwcWc3R2tBUU5JTVJpN2ZpdmNXZTE5SjZWTE0KbFVrSzJiVzgxaTMveDNBdldLTjJYbit6K1ZvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
