apiVersion: v1
kind: Service
metadata:
  name: node-app1-service
spec:
  selector:
    app: node-app1
  type: LoadBalancer 
  ports:
    - protocol: TCP
      name: https-napp1
      port: 3000
      targetPort: 3000
      nodePort: 31000
