apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2-deployment
spec:
  selector:
    matchLabels:
      app: node-app2
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app2
    spec:
      containers:
        - name: node-app2
          image: tomras/thes-node-app2
          ports:
            - containerPort: 3001
          env:
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            value: ${DB_PASS}
          - name: DB_HOST
            value: database-postgresql
