apiVersion: v1
kind: Service
metadata:
  name: node-app2-service
spec:
  selector:
    app: node-app2
  type: LoadBalancer 
  ports:
    - protocol: TCP
      name: https-napp2
      port: 3001
      targetPort: 3001
      nodePort: 31001
