# Use this for non-Istio testing to make services directly accessible
apiVersion: v1
kind: Service
metadata:
  name: uid-app2-service
spec:
  selector:
    app: uid-app2
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 5000
